<a href="https://colab.research.google.com/github/Saranyanv/data-go/blob/master/Misc/sudoku_solver_v2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
import random

def difference(list1):
   list_dif = [i for i in list1 + [1,2,3,4,5,6,7,8,9] if (i not in list1 or i not in [1,2,3,4,5,6,7,8,9]) and i!=0]
   return list_dif

def uniq_append(element, list1):
  if element not in list1 and element!=0:
    list1.append(element)

def dupcheck(row_num, col_num, arg_list):
  tmp_dict={}
  for i in [abs(i) for i in arg_list[row_num] if i!=0]:
    if i not in tmp_dict.keys():
      tmp_dict[i]=0
    else:
      return 'Dups'
  
  tmp_dict={}
  for n in range(9):
    if arg_list[n][col_num]==0:
      pass
    elif abs(arg_list[n][col_num]) not in tmp_dict.keys():
      tmp_dict[abs(arg_list[n][col_num])]=0
    else:
      return 'Dups'
    
  tmp_dict={}
  for i1 in range(row_num-np.mod(row_num,3), row_num+np.mod(8-row_num,3)+1):
    for j1 in range(col_num-np.mod(col_num,3), col_num+np.mod(8-col_num,3)+1):
      if arg_list[i1][j1]==0:
        pass
      elif abs(arg_list[i1][j1]) not in tmp_dict.keys():
        tmp_dict[abs(arg_list[i1][j1])]=0
      else:
        return 'Dups'

In [266]:
d1=dupcheck(3,8,arr)
print (d1)

Dups in Square


In [0]:
rows, cols = (9, 9) 
#arr = [[random.randint(0,9) for i in range(rows)] for i in range(cols)]

#Difficulty=Easy
#arr=[[5,2,4,6,0,0,0,0,1],[0,1,0,8,4,3,0,6,5],[3,0,0,0,1,0,0,0,0],[7,5,2,0,0,0,1,0,0],[0,0,0,1,0,7,0,0,0],[0,0,6,0,0,0,7,5,8],[0,0,0,0,9,0,0,0,2],[4,7,0,2,8,6,0,1,0],[2,0,0,0,0,5,6,7,9]]

#Difficulty=Medium
#arr=[[0,0,9,0,8,2,0,0,5],[0,0,0,9,0,0,1,0,0],[0,5,3,1,0,0,9,8,7],[3,0,7,0,9,1,0,0,0],[0,0,0,0,0,0,0,0,0],[0,0,0,6,2,0,3,0,9],[6,9,5,0,0,8,4,3,0],[0,0,4,0,0,9,0,0,0],[1,0,0,4,3,0,5,0,0]]
#arr=[[3,0,8,0,0,6,0,0,9],[0,9,0,8,0,0,0,4,2],[0,0,0,0,1,0,0,8,0],[0,6,0,0,0,0,2,0,0],[1,0,0,3,5,2,0,0,6],[0,0,3,0,0,0,0,9,0],[0,3,0,0,4,0,0,0,0],[5,1,0,0,0,8,0,2,0],[8,0,0,2,0,0,1,0,5]]
arr=[[0,8,0,5,0,6,4,2,0],
     [7,0,5,0,0,0,9,0,0],
     [0,0,4,0,3,0,0,0,5],
     [3,0,0,7,0,0,0,0,8],
     [0,0,0,0,8,0,0,0,0],
     [6,0,0,0,0,1,0,0,2],
     [2,0,0,0,4,0,5,0,0],
     [0,0,6,0,0,0,2,0,4],
     [0,4,1,6,0,5,0,7,0]]

In [366]:
#old
arr

[[0, 8, 0, 5, 0, 6, 4, 2, 0],
 [7, 0, 5, 0, 0, 0, 9, 0, 0],
 [0, 0, 4, 0, 3, 0, 0, 0, 5],
 [3, 0, 0, 7, 0, 0, 0, 0, 8],
 [0, 0, 0, 0, 8, 0, 0, 0, 0],
 [6, 0, 0, 0, 0, 1, 0, 0, 2],
 [2, 0, 0, 0, 4, 0, 5, 0, 0],
 [0, 0, 6, 0, 0, 0, 2, 0, 4],
 [0, 4, 1, 6, 0, 5, 0, 7, 0]]

In [0]:
def sudoku(arg_list):
  dict1={}
  cntr=0;prev_not_filled=0;offset=1;C=0
  backup_arr=arg_list
  while True:
    print ("Pass Nbr #",cntr)
    for i in range(rows):
      for j in range(cols):
        #print ("i=",i,"j=",j)
        if arg_list[i][j]==0:
          dup_chk=dupcheck(i,j,arr)
          if dup_chk=='Dups':
            print ("Resetting due to Dups")
            arg_list=backup_arr
            C+=1
            continue
          else:
            #get numbers in that row
            tmp=[abs(i) for i in arg_list[i] if i!=0]
            #get numbers in that column
            for n in range(rows):
              uniq_append(abs(arg_list[n][j]),tmp)
            #get numbers in that square
            for i1 in range(i-np.mod(i,3), i+np.mod(8-i,3)+1):
              for j1 in range(j-np.mod(j,3), j+np.mod(8-j,3)+1):
                uniq_append(abs(arg_list[i1][j1]),tmp)
            if len(difference(tmp))==1:
              arg_list[i][j]=offset*sum(int(x) for x in difference(tmp))
              #dict1[(i*10)+j]=[]
              dict1[tuple([i,j])]=[]
            elif len(difference(tmp))>1:
              #dict1[(i*10)+j]=difference(tmp)
              dict1[tuple([i,j])]=difference(tmp)
    not_filled=len([i for j in arg_list for i in j if i==0])
    if prev_not_filled==not_filled:
      offset=-1
      (postn,likely_val)=[(k,v[C]) for k,v in dict1.items() if len(v)==min([len(i) for i in dict1.values() if i!=[]])][0]
      arr[postn[0]][postn[1]]=offset*likely_val
      dict1[tuple([postn[0],postn[1]])]=[]
      #print ("Count not proceed!")
      #print ("probabilistic computation...")
      print (postn,likely_val, dict1)
      #return dict1
      #break
    elif not_filled>0:
      print ("  Number of unfilled positions is ",not_filled)
      #print(np.matrix(arg_list))
      prev_not_filled=not_filled
    else:
      print ("Sudoku Challenge complete in",cntr,"passes!")
      print (" ")
      print(np.matrix(arg_list))
      return False
    cntr+=1

In [369]:
d1=sudoku(arr)

Pass Nbr # 0
  Number of unfilled positions is  52
Pass Nbr # 1
(0, 0) 1 {(0, 0): [], (0, 2): [3, 9], (0, 4): [1, 7, 9], (0, 8): [1, 3, 7], (1, 1): [1, 2, 3, 6], (1, 3): [1, 2, 4, 8], (1, 4): [1, 2], (1, 5): [2, 4, 8], (1, 7): [1, 3, 6, 8], (1, 8): [1, 3, 6], (2, 0): [1, 9], (2, 1): [1, 2, 6, 9], (2, 3): [1, 2, 8, 9], (2, 5): [2, 7, 8, 9], (2, 6): [1, 6, 7, 8], (2, 7): [1, 6, 8], (3, 1): [1, 2, 5, 9], (3, 2): [2, 9], (3, 4): [2, 5, 6, 9], (3, 5): [2, 4, 9], (3, 6): [1, 6], (3, 7): [1, 4, 5, 6, 9], (4, 0): [1, 4, 5, 9], (4, 1): [1, 2, 5, 7, 9], (4, 2): [2, 7, 9], (4, 3): [2, 3, 4, 9], (4, 5): [2, 3, 4, 9], (4, 6): [1, 3, 6, 7], (4, 7): [1, 3, 4, 5, 6, 9], (4, 8): [1, 3, 6, 7, 9], (5, 1): [5, 7, 9], (5, 2): [7, 8, 9], (5, 3): [3, 4, 9], (5, 4): [5, 9], (5, 6): [3, 7], (5, 7): [3, 4, 5, 9], (6, 1): [3, 7, 9], (6, 2): [3, 7, 8, 9], (6, 3): [1, 3, 8, 9], (6, 5): [3, 7, 8, 9], (6, 7): [1, 3, 6, 8, 9], (6, 8): [1, 3, 6, 9], (7, 0): [5, 8, 9], (7, 1): [3, 5, 7, 9], (7, 3): [1, 3, 8, 9], (7, 4)

In [370]:
#new
print(np.matrix(arr))

[[-1  8 -3  5 -9  6  4  2 -7]
 [ 7 -2  5 -4 -1 -8  9 -3 -6]
 [-9 -6  4 -2  3 -7 -8 -1  5]
 [ 3 -5 -2  7 -6 -4 -1 -9  8]
 [-4 -1 -7 -9  8 -2 -6 -5 -3]
 [ 6 -9 -8 -3 -5  1 -7 -4  2]
 [ 2 -7 -9 -8  4 -3  5 -6 -1]
 [-5 -3  6 -1 -7 -9  2 -8  4]
 [-8  4  1  6 -2  5 -3  7 -9]]
